// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Group2Project.Models;

public partial class NbaContext : DbContext
{
    public NbaContext()
    {
    }

    public NbaContext(DbContextOptions<NbaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Player> Players { get; set; }

    public virtual DbSet<PlayerStat> PlayerStats { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
         =>optionsBuilder.UseSqlServer("Data Source=tcp:s30.winhost.com;" +"Initial Catalog=DB_128040_group2;" +"Persist Security Info=True;" +"User ID=DB_128040_group2_user;" +"Password=Net9;" +"Encrypt=False;" +"TrustServerCertificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Player>(entity =>
        {
            entity.HasKey(e => e.PlayerKey).HasName("PK__Players__85CA2E9F9886A67D");

            entity.Property(e => e.Age).HasColumnName("age");
            entity.Property(e => e.Lg)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("lg");
            entity.Property(e => e.Player1)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("player");
            entity.Property(e => e.PlayerId)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("player_id");
            entity.Property(e => e.Pos)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("pos");
            entity.Property(e => e.Season).HasColumnName("season");
            entity.Property(e => e.Team)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("team");
        });

        modelBuilder.Entity<PlayerStat>(entity =>
        {
            entity.HasKey(e => e.StatsId).HasName("PK__PlayerSt__C23A1EA3568C875A");

            entity.Property(e => e.Ast).HasColumnName("ast");
            entity.Property(e => e.Blk).HasColumnName("blk");
            entity.Property(e => e.Drb).HasColumnName("drb");
            entity.Property(e => e.EFgPercent).HasColumnName("e_fg_percent");
            entity.Property(e => e.Fg).HasColumnName("fg");
            entity.Property(e => e.FgPercent).HasColumnName("fg_percent");
            entity.Property(e => e.Fga).HasColumnName("fga");
            entity.Property(e => e.Ft).HasColumnName("ft");
            entity.Property(e => e.FtPercent).HasColumnName("ft_percent");
            entity.Property(e => e.Fta).HasColumnName("fta");
            entity.Property(e => e.G).HasColumnName("g");
            entity.Property(e => e.Gs).HasColumnName("gs");
            entity.Property(e => e.Mp).HasColumnName("mp");
            entity.Property(e => e.Orb).HasColumnName("orb");
            entity.Property(e => e.Pf).HasColumnName("pf");
            entity.Property(e => e.PlayerId)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("player_id");
            entity.Property(e => e.Pts).HasColumnName("pts");
            entity.Property(e => e.Stl).HasColumnName("stl");
            entity.Property(e => e.Tov).HasColumnName("tov");
            entity.Property(e => e.Trb).HasColumnName("trb");
            entity.Property(e => e.TrpDbl).HasColumnName("trp_dbl");
            entity.Property(e => e.X2p).HasColumnName("x2p");
            entity.Property(e => e.X2pPercent).HasColumnName("x2p_percent");
            entity.Property(e => e.X2pa).HasColumnName("x2pa");
            entity.Property(e => e.X3p).HasColumnName("x3p");
            entity.Property(e => e.X3pPercent).HasColumnName("x3p_percent");
            entity.Property(e => e.X3pa).HasColumnName("x3pa");

            entity.HasOne(d => d.PlayerKeyNavigation).WithMany(p => p.PlayerStats)
                .HasForeignKey(d => d.PlayerKey)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlayerStats_Players");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}