// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPFApplication.Models;

public partial class Player
{
    public int PlayerKey { get; set; }

    public string PlayerId { get; set; }

    public string Player1 { get; set; }

    public int? Age { get; set; }

    public string Team { get; set; }

    public string Pos { get; set; }

    public int? Season { get; set; }

    public string Lg { get; set; }

    public virtual ICollection<PlayerStat> PlayerStats { get; set; } = new List<PlayerStat>();
}