// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPFApplication.Models;

public partial class PlayerStat
{
    public int StatsId { get; set; }

    public string PlayerId { get; set; }

    public int? G { get; set; }

    public int? Gs { get; set; }

    public double? Mp { get; set; }

    public int? Fg { get; set; }

    public int? Fga { get; set; }

    public double? FgPercent { get; set; }

    public int? X3p { get; set; }

    public int? X3pa { get; set; }

    public double? X3pPercent { get; set; }

    public int? X2p { get; set; }

    public int? X2pa { get; set; }

    public double? X2pPercent { get; set; }

    public double? EFgPercent { get; set; }

    public int? Ft { get; set; }

    public int? Fta { get; set; }

    public double? FtPercent { get; set; }

    public double? Orb { get; set; }

    public double? Drb { get; set; }

    public double? Trb { get; set; }

    public double? Ast { get; set; }

    public double? Stl { get; set; }

    public double? Blk { get; set; }

    public double? Tov { get; set; }

    public double? Pf { get; set; }

    public int? Pts { get; set; }

    public double? TrpDbl { get; set; }

    public int PlayerKey { get; set; }

    public int? Season { get; set; }

    public virtual Player PlayerKeyNavigation { get; set; }
}